ifeq ($(CONFIG_OPPO_FINGERPRINT),y)
obj-y        += oppo_fp_common/
obj-y        += fpc/

obj-y        += goodix_optical_fp/
obj-y        += silead/
obj-y        += egis/
endif

subdir-ccflags-y += -DCONFIG_OPPO_FINGERPRINT_PROJCT=18041
